# @name login
POST {{baseUrl}}/v1/auth/login
Content-Type: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{adminPassword}}"
}

###
# @name createCurrency
POST {{baseUrl}}/v1/currencies
Authorization: Bearer {{login.response.body.data.access_token}}
Content-Type: application/json

{
  "code": "T{{$timestamp}}",
  "name": "Test Currency",
  "symbol": "$",
  "exchange_rate_to_php": 1.25
}

###
# @name listCurrencies
GET {{baseUrl}}/v1/currencies?limit=20&page=1
Authorization: Bearer {{login.response.body.data.access_token}}

###
# @name getCurrency
GET {{baseUrl}}/v1/currencies/{{createCurrency.response.body.id}}
Authorization: Bearer {{login.response.body.data.access_token}}

###
# @name updateCurrency
PATCH {{baseUrl}}/v1/currencies/{{createCurrency.response.body.id}}
Authorization: Bearer {{login.response.body.data.access_token}}
Content-Type: application/json

{
  "name": "Philippine Peso",
  "symbol": "PHP"
}

###
# @name deleteCurrency
DELETE {{baseUrl}}/v1/currencies/{{createCurrency.response.body.id}}
Authorization: Bearer {{login.response.body.data.access_token}}
