import { ApiProperty } from '@nestjs/swagger';
import { Exclude } from 'class-transformer';

/**
 * Simplified domain entity for sub-section lookup operations.
 *
 * This domain entity represents a lightweight sub-section object containing
 * only essential fields for lookup and selection operations. It's optimized
 * for API responses and client-side operations where full entity data
 * is not required.
 *
 * @version 3
 * @since 1.0.0
 * @author Masters Module Team
 *
 * @example
 * ```typescript
 * const lookupEntity = new FindAllSubSection();
 * lookupEntity.id = 1;
 * lookupEntity.sub_section_code = '01';
 * lookupEntity.sub_section_name = 'Backend';
 * ```
 */
export class FindAllSubSection {
  /**
   * Unique identifier for the sub-section.
   *
   * This field serves as the primary key for the sub-section and is
   * automatically generated by the database. It uniquely identifies
   * each sub-section in the system.
   *
   * @example 1
   * @example 123
   */
  @ApiProperty({
    type: Number,
    example: 1,
  })
  id: number;

  /**
   * Unique business code for the sub-section.
   *
   * This field represents the human-readable business code for the sub-section.
   * It must be unique across all sub-sections and follows a specific format.
   * The code is used for business operations and reporting.
   *
   * @example '00'
   * @example '01'
   * @example '99'
   */
  @ApiProperty({
    type: () => String,
    nullable: false,
    example: '00',
  })
  sub_section_code: string;

  /**
   * Human-readable name of the sub-section.
   *
   * This field contains the display name for the sub-section used in
   * user interfaces and reports. It should be descriptive and
   * clearly identify the sub-section's purpose or function.
   *
   * @example 'Backend'
   * @example 'Frontend'
   * @example 'DevOps'
   */
  @ApiProperty({
    type: () => String,
    nullable: false,
    example: 'Backend',
  })
  sub_section_name: string;

  /**
   * Internal entity type identifier.
   *
   * This field is used internally by the system for entity type
   * identification and is excluded from API responses. It helps
   * with type checking and entity management within the application.
   *
   * @example 'FindAllSubSection'
   */
  @Exclude()
  __entity?: string;
}
