import { ApiProperty } from '@nestjs/swagger';
import { User } from '@/users/domain/user';
import { Exclude } from 'class-transformer';
import { StatusEnum } from '@/utils/enums/status-enum';
import { Causer } from '@/utils/domain/causer';

/**
 * Domain entity representing a sub-section in the organizational hierarchy.
 *
 * This domain entity represents a complete sub-section with all properties,
 * relationships, and audit information. It serves as the primary business
 * object for sub-section operations and includes comprehensive data for
 * organizational management.
 *
 * @version 3
 * @since 1.0.0
 * @author Masters Module Team
 *
 * @example
 * ```typescript
 * const subSection = new SubSection();
 * subSection.id = 1;
 * subSection.sub_section_code = '01';
 * subSection.sub_section_name = 'Backend';
 * subSection.sub_section_head = user;
 * subSection.status = StatusEnum.ACTIVE;
 * ```
 */
export class SubSection {
  /**
   * Unique identifier for the sub-section.
   *
   * This field serves as the primary key for the sub-section and is
   * automatically generated by the database. It uniquely identifies
   * each sub-section in the system.
   *
   * @example 1
   * @example 123
   */
  @ApiProperty({
    type: Number,
    example: 1,
  })
  id: number;

  /**
   * Unique business code for the sub-section.
   *
   * This field represents the human-readable business code for the sub-section.
   * It must be unique across all sub-sections and follows a specific format.
   * The code is used for business operations and reporting.
   *
   * @example '00'
   * @example '01'
   * @example '99'
   */
  @ApiProperty({
    type: String,
    nullable: false,
    example: '00',
  })
  sub_section_code: string;

  /**
   * Human-readable name of the sub-section.
   *
   * This field contains the display name for the sub-section used in
   * user interfaces and reports. It should be descriptive and
   * clearly identify the sub-section's purpose or function.
   *
   * @example 'Backend'
   * @example 'Frontend'
   * @example 'DevOps'
   */
  @ApiProperty({
    type: String,
    nullable: false,
    example: 'Backend',
  })
  sub_section_name: string;

  /**
   * The user who serves as the head of the sub-section.
   *
   * This field represents the person responsible for leading the sub-section.
   * It contains essential user information including ID, name, and
   * cost center for organizational hierarchy management.
   *
   * @example { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' }
   */
  @ApiProperty({
    type: () => User,
    nullable: false,
    example: { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' },
  })
  sub_section_head: Pick<
    User,
    'id' | 'first_name' | 'last_name' | 'cost_center'
  >;

  /**
   * Current status of the sub-section.
   *
   * This field indicates the operational status of the sub-section.
   * Valid values include Active, Hold, and Cancelled. The status
   * determines whether the sub-section is operational and available
   * for business processes.
   *
   * @example StatusEnum.ACTIVE
   * @example StatusEnum.HOLD
   * @example StatusEnum.CANCELLED
   */
  @ApiProperty({
    type: String,
    nullable: false,
    example: StatusEnum.ACTIVE,
  })
  status: string;

  /**
   * The user who created the sub-section.
   *
   * This field tracks the user responsible for creating the sub-section.
   * It contains essential user information for audit purposes and
   * accountability tracking in the system.
   *
   * @example { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' }
   */
  @ApiProperty({
    type: () => User,
    nullable: false,
    example: { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' },
  })
  created_by: Causer;

  /**
   * Timestamp when the sub-section was created.
   *
   * This field records the exact date and time when the sub-section
   * was first created in the system. It's automatically set by
   * the database and used for audit trails and reporting.
   *
   * @example new Date('2024-01-15T10:30:00Z')
   */
  @ApiProperty()
  created_at: Date;

  /**
   * The user who last updated the sub-section.
   *
   * This field tracks the user responsible for the most recent update
   * to the sub-section. It contains essential user information for
   * audit purposes and change tracking in the system.
   *
   * @example { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' }
   */
  @ApiProperty({
    type: () => User,
    nullable: false,
    example: { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' },
  })
  updated_by: Causer;

  /**
   * Timestamp when the sub-section was last updated.
   *
   * This field records the exact date and time when the sub-section
   * was most recently modified. It's automatically updated by
   * the database and used for audit trails and change tracking.
   *
   * @example new Date('2024-01-20T14:45:00Z')
   */
  @ApiProperty()
  updated_at: Date;

  /**
   * The user who deleted the sub-section.
   *
   * This field tracks the user responsible for deleting the sub-section.
   * It's only populated when the sub-section is soft deleted and
   * contains essential user information for audit purposes.
   *
   * @example null
   * @example { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' }
   */
  @ApiProperty({
    type: () => User,
    nullable: true,
    example: null,
  })
  deleted_by?: Causer | null;

  /**
   * Timestamp when the sub-section was deleted.
   *
   * This field records the exact date and time when the sub-section
   * was soft deleted. It's only populated when the sub-section is
   * deleted and used for audit trails and data recovery purposes.
   *
   * @example null
   * @example new Date('2024-01-25T16:30:00Z')
   */
  @ApiProperty({
    example: null,
  })
  deleted_at?: Date | null;

  /**
   * Internal entity type identifier.
   *
   * This field is used internally by the system for entity type
   * identification and is excluded from API responses. It helps
   * with type checking and entity management within the application.
   *
   * @example 'SubSection'
   */
  @Exclude()
  __entity?: string;
}
