import { UserEntity } from '@/users/persistence/entities/user.entity';
import { EntityHelper } from '@/utils/entity-helper';
import {
  CreateDateColumn,
  DeleteDateColumn,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

/**
 * Abstract base class providing common helper functionality for entities in the application.
 * Includes fields for tracking creation, updates, and deletion metadata, and links to a user entity
 * representing who created, updated, or deleted the entity.
 *
 * @extends EntityHelper
 */
export abstract class BaseEntityHelper extends EntityHelper {
  /**
   * Unique identifier for the entity.
   * Automatically generated by the database.
   *
   * @type {number}
   * @memberof BaseEntityHelper
   */
  @PrimaryGeneratedColumn()
  id: number;

  /**
   * The user who created the entity.
   * Nullable in case there is no associated user.
   *
   * @type {UserEntity | null}
   * @memberof BaseEntityHelper
   */
  @ManyToOne(() => UserEntity, { eager: false, nullable: true })
  @JoinColumn({ name: 'created_by' })
  created_by: UserEntity | null;

  /**
   * Timestamp when the entity was created.
   * Automatically set to the current date and time when the entity is created.
   *
   * @type {Date}
   * @memberof BaseEntityHelper
   */
  @CreateDateColumn({ type: 'timestamptz' })
  created_at: Date;

  /**
   * The user who last updated the entity.
   * Nullable in case there is no associated user for the last update.
   *
   * @type {UserEntity | null}
   * @memberof BaseEntityHelper
   */
  @ManyToOne(() => UserEntity, { eager: false, nullable: true })
  @JoinColumn({ name: 'updated_by' })
  updated_by: UserEntity | null;

  /**
   * Timestamp of the last update to the entity.
   * Automatically updated to the current date and time whenever the entity is updated.
   *
   * @type {Date}
   * @memberof BaseEntityHelper
   */
  @UpdateDateColumn({ type: 'timestamptz' })
  updated_at: Date;

  /**
   * The user who marked the entity as deleted.
   * Nullable in case no user is associated with the deletion.
   *
   * @type {UserEntity | null}
   * @memberof BaseEntityHelper
   */
  @ManyToOne(() => UserEntity, { eager: false, nullable: true })
  @JoinColumn({ name: 'deleted_by' })
  deleted_by?: UserEntity | null;

  /**
   * Timestamp of when the entity was deleted.
   * Nullable in case the entity was not deleted.
   *
   * @type {Date | null}
   * @memberof BaseEntityHelper
   */
  @DeleteDateColumn({ type: 'timestamptz' })
  deleted_at?: Date | null;
}
