import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsString,
  Matches,
  IsOptional,
  ValidateIf,
  IsNotEmpty,
  IsEnum,
} from 'class-validator';
import { StatusEnum } from '@/utils/enums/status-enum';

/**
 * Create Cost Center Data Transfer Object
 *
 * DTO for creating new cost centers with hierarchical organization structure.
 * Validates the organizational hierarchy and ensures proper code generation
 * based on division, department, section, and sub-section codes.
 *
 * The cost center code is automatically generated by combining the provided
 * organizational codes in the format: {division}{department}{section}{sub_section}
 *
 * @example
 * ```typescript
 * const createDto: CreateCostCenterDto = {
 *   division: '01',
 *   department: '01',
 *   section: '01',
 *   sub_section: '01',
 *   remarks: 'Backend Development Team',
 *   status: StatusEnum.ACTIVE
 * };
 * // Will generate cost_center_code: '01010101'
 * ```
 *
 * @author Cody Inc Development Team
 * @since 1.0.0
 */
export class CreateCostCenterDto {
  @ApiProperty({ type: String, required: true, example: '00' })
  @IsString()
  @Matches(/^(0[0-9]|[1-9][0-9])$/, {
    message: 'Division must only contain numbers between 00 and 99',
  })
  division: string;

  @ApiPropertyOptional({ type: String, required: false, example: '01' })
  @ValidateIf((o) => o.section)
  @IsNotEmpty({ message: 'Department is required when Section is provided' })
  @IsString()
  @Matches(/^(0[0-9]|[1-9][0-9])$/, {
    message: 'Department must only contain numbers between 00 and 99',
  })
  department: string;

  @ApiPropertyOptional({ type: String, required: false, example: '02' })
  @ValidateIf((o) => o.sub_section)
  @IsNotEmpty({ message: 'Section is required when SubSection is provided' })
  @IsString()
  @Matches(/^(0[0-9]|[1-9][0-9])$/, {
    message: 'Section must only contain numbers between 00 and 99',
  })
  section: string;

  @ApiPropertyOptional({ type: String, required: false, example: '03' })
  @IsOptional()
  @IsString()
  @Matches(/^(0[0-9]|[1-9][0-9])$/, {
    message: 'SubSection must only contain numbers between 00 and 99',
  })
  sub_section: string;

  @ApiPropertyOptional({
    type: String,
    required: false,
    example: 'To be used by SD1 Backend Engineers',
  })
  @IsOptional()
  @IsString()
  remarks?: string;

  @ApiPropertyOptional({
    type: String,
    enum: StatusEnum,
    description: 'Cost Center status',
    default: StatusEnum.ACTIVE,
    example: StatusEnum.ACTIVE,
  })
  @IsOptional()
  @IsEnum(StatusEnum, {
    message: 'status must be a valid status from the enum',
  })
  status?: StatusEnum;
}
