export enum ParameterCode {
  AUTO_GENERATE_SUPPLIER_CODE = 'AUTO_GENERATE_SUPPLIER_CODE',
  ENABLE_INVENTORY_ENTRY_DURING_COUNT = 'ENABLE_INVENTORY_ENTRY_DURING_COUNT',
  RETURN_WINDOW_DAYS = 'RETURN_WINDOW_DAYS',
  SCHEDULE_TIME_STORAGE_MODE = 'schedule_time_storage_mode',
  SCHEDULE_TIMEZONE = 'schedule_timezone',
}
