import { ApiProperty } from '@nestjs/swagger';
import { Exclude } from 'class-transformer';
import { User } from '@/users/domain/user';
import { StatusEnum } from '@/utils/enums/status-enum';
import { Causer } from '@/utils/domain/causer';

/**
 * Domain entity representing a division in the organizational hierarchy.
 *
 * This domain entity represents a complete division with all properties,
 * relationships, and audit information. It serves as the primary business
 * object for division operations and includes all necessary fields for
 * API documentation and validation.
 *
 * @version 3
 * @since 1.0.0
 * @author Masters Module Team
 *
 * @example
 * ```typescript
 * const division = new Division();
 * division.division_code = '01';
 * division.division_name = 'Engineering';
 * division.division_head = user;
 * ```
 */
export class Division {
  /**
   * Unique identifier for the division.
   *
   * This field serves as the primary key for the division entity
   * and is automatically generated by the database.
   *
   * @example 1
   */
  @ApiProperty({
    type: Number,
    example: 1,
  })
  id: number;

  /**
   * Unique business code for the division.
   *
   * This field represents the human-readable business code for the division.
   * It must be unique across all divisions and follows a specific format.
   * The code is used for business operations and reporting.
   *
   * @example '00'
   * @example '01'
   */
  @ApiProperty({
    type: String,
    nullable: false,
    example: '00',
  })
  division_code: string;

  /**
   * Human-readable name of the division.
   *
   * This field contains the display name for the division used in
   * user interfaces and reports. It should be descriptive and
   * clearly identify the division's purpose or function.
   *
   * @example 'Engineering'
   * @example 'Marketing'
   * @example 'Sales'
   */
  @ApiProperty({
    type: String,
    nullable: false,
    example: 'CODY',
  })
  division_name: string;

  /**
   * The user who serves as the head of the division.
   *
   * This field represents the person responsible for leading the division.
   * It contains essential user information including ID, name, and cost center.
   * The division head is responsible for managing the division's operations.
   *
   * @example { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' }
   */
  @ApiProperty({
    type: () => User,
    nullable: false,
    example: { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' },
  })
  division_head: Pick<User, 'id' | 'first_name' | 'last_name' | 'cost_center'>;

  /**
   * Current status of the division.
   *
   * This field indicates the operational status of the division.
   * Valid values include Active, Hold, and Cancelled. The status
   * determines whether the division is operational and available
   * for business processes.
   *
   * @example 'Active'
   * @example 'Hold'
   * @example 'Cancelled'
   */
  @ApiProperty({
    type: String,
    nullable: false,
    example: StatusEnum.ACTIVE,
  })
  status: string;

  /**
   * User who created the division.
   *
   * This field tracks the user who originally created the division.
   * It contains essential user information for audit purposes and
   * accountability tracking.
   *
   * @example { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' }
   */
  @ApiProperty({
    type: () => User,
    nullable: false,
    example: { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' },
  })
  created_by: Causer;

  /**
   * Timestamp when the division was created.
   *
   * This field records the exact date and time when the division
   * was first created in the system. It's used for audit purposes
   * and chronological tracking.
   *
   * @example "2024-01-15T10:30:00.000Z"
   */
  @ApiProperty()
  created_at: Date;

  /**
   * User who last updated the division.
   *
   * This field tracks the user who made the most recent changes
   * to the division. It contains essential user information for
   * audit purposes and change tracking.
   *
   * @example { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' }
   */
  @ApiProperty({
    type: () => User,
    nullable: false,
    example: { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' },
  })
  updated_by: Causer;

  /**
   * Timestamp when the division was last updated.
   *
   * This field records the exact date and time when the division
   * was last modified. It's used for audit purposes and change
   * tracking to identify when updates occurred.
   *
   * @example "2024-01-15T14:30:00.000Z"
   */
  @ApiProperty()
  updated_at: Date;

  /**
   * User who deleted the division (if applicable).
   *
   * This field tracks the user who performed the soft delete operation
   * on the division. It's null for active divisions and contains user
   * information for deleted divisions.
   *
   * @example null
   * @example { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' }
   */
  @ApiProperty({
    type: () => User,
    nullable: true,
    example: null,
  })
  deleted_by?: Causer | null;

  /**
   * Timestamp when the division was deleted (if applicable).
   *
   * This field records the exact date and time when the division
   * was soft deleted. It's null for active divisions and contains
   * the deletion timestamp for deleted divisions.
   *
   * @example null
   * @example "2024-01-15T16:30:00.000Z"
   */
  @ApiProperty({
    example: null,
  })
  deleted_at?: Date | null;

  /**
   * Internal entity identifier for TypeORM.
   *
   * This field is used internally by TypeORM for entity management
   * and is excluded from serialization to prevent exposure in API responses.
   *
   * @example 'DivisionEntity'
   */
  @Exclude()
  __entity?: string;
}
