import { ApiProperty } from '@nestjs/swagger';
import { User } from '@/users/domain/user';
import { Exclude } from 'class-transformer';
import { StatusEnum } from '@/utils/enums/status-enum';
import { Causer } from '@/utils/domain/causer';

/**
 * Domain entity representing a section in the organizational hierarchy.
 *
 * This domain entity represents a complete section with all properties,
 * relationships, and audit information. It serves as the primary business
 * object for section operations and includes comprehensive data for
 * organizational management.
 *
 * @version 3
 * @since 1.0.0
 * @author Masters Module Team
 *
 * @example
 * ```typescript
 * const section = new Section();
 * section.id = 1;
 * section.section_code = '01';
 * section.section_name = 'Engineering';
 * section.section_head = user;
 * section.status = StatusEnum.ACTIVE;
 * ```
 */
export class Section {
  /**
   * Unique identifier for the section.
   *
   * This field serves as the primary key for the section and is
   * automatically generated by the database. It uniquely identifies
   * each section in the system.
   *
   * @example 1
   * @example 123
   */
  @ApiProperty({
    type: Number,
    example: 1,
  })
  id: number;

  /**
   * Unique business code for the section.
   *
   * This field represents the human-readable business code for the section.
   * It must be unique across all sections and follows a specific format.
   * The code is used for business operations and reporting.
   *
   * @example '00'
   * @example '01'
   * @example '99'
   */
  @ApiProperty({
    type: String,
    nullable: false,
    example: '01',
  })
  section_code: string;

  /**
   * Human-readable name of the section.
   *
   * This field contains the display name for the section used in
   * user interfaces and reports. It should be descriptive and
   * clearly identify the section's purpose or function.
   *
   * @example 'Engineering'
   * @example 'Marketing'
   * @example 'Sales'
   */
  @ApiProperty({
    type: String,
    nullable: false,
    example: 'SD1',
  })
  section_name: string;

  /**
   * The user who serves as the head of the section.
   *
   * This field represents the person responsible for leading the section.
   * It contains essential user information including ID, name, and
   * cost center for organizational hierarchy management.
   *
   * @example { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' }
   */
  @ApiProperty({
    type: () => User,
    nullable: false,
    example: { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' },
  })
  section_head: Pick<User, 'id' | 'first_name' | 'last_name' | 'cost_center'>;

  /**
   * Current status of the section.
   *
   * This field indicates the operational status of the section.
   * Valid values include Active, Hold, and Cancelled. The status
   * determines whether the section is operational and available
   * for business processes.
   *
   * @example StatusEnum.ACTIVE
   * @example StatusEnum.HOLD
   * @example StatusEnum.CANCELLED
   */
  @ApiProperty({
    type: String,
    nullable: false,
    example: StatusEnum.ACTIVE,
  })
  status: string;

  /**
   * User who created the section.
   *
   * This field tracks the user who originally created the section.
   * It contains essential user information for audit purposes and
   * change tracking in the organizational hierarchy.
   *
   * @example { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' }
   */
  @ApiProperty({
    type: () => User,
    nullable: false,
    example: { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' },
  })
  created_by: Causer;

  /**
   * Timestamp when the section was created.
   *
   * This field records the exact date and time when the section
   * was first created in the system. It's automatically managed
   * and used for audit purposes and change tracking.
   *
   * @example "2024-01-15T10:30:00.000Z"
   */
  @ApiProperty()
  created_at: Date;

  /**
   * User who last updated the section.
   *
   * This field tracks the user who made the most recent changes
   * to the section. It contains essential user information for
   * audit purposes and change tracking in the organizational hierarchy.
   *
   * @example { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' }
   */
  @ApiProperty({
    type: () => User,
    nullable: false,
    example: { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' },
  })
  updated_by: Causer;

  /**
   * Timestamp when the section was last updated.
   *
   * This field records the exact date and time when the section
   * was last modified. It's automatically managed and used for
   * audit purposes and change tracking.
   *
   * @example "2024-01-15T14:30:00.000Z"
   */
  @ApiProperty()
  updated_at: Date;

  /**
   * User who deleted the section (if applicable).
   *
   * This field tracks the user who performed the soft delete operation
   * on the section. It's null for active sections and contains user
   * information for deleted sections. Used for audit purposes.
   *
   * @example null
   * @example { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' }
   */
  @ApiProperty({
    type: () => User,
    nullable: true,
    example: null,
  })
  deleted_by?: Causer | null;

  /**
   * Timestamp when the section was deleted (if applicable).
   *
   * This field records the exact date and time when the section
   * was soft deleted. It's null for active sections and contains
   * the deletion timestamp for deleted sections. Used for audit purposes.
   *
   * @example null
   * @example "2024-01-15T16:30:00.000Z"
   */
  @ApiProperty({
    example: null,
  })
  deleted_at?: Date | null;

  /**
   * Internal entity type identifier.
   *
   * This field is used internally for entity type identification
   * and is excluded from serialization. It helps with type
   * checking and entity management in the system.
   *
   * @example "Section"
   */
  @Exclude()
  __entity?: string;
}
