import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsInt } from 'class-validator';

/**
 * Data Transfer Object for identifying a sub-section by its ID.
 *
 * This DTO defines the required field needed to identify
 * a sub-section in the system. It includes validation rules
 * for the ID field ensuring data integrity and consistency.
 *
 * @version 3
 * @since 1.0.0
 * @author Masters Module Team
 */
export class SubSectionDto {
  /**
   * Unique identifier for the sub-section.
   *
   * This field serves as the primary key for the sub-section and is
   * automatically generated by the database. It uniquely identifies
   * each sub-section in the system.
   *
   * @example 1
   * @example 123
   */
  @ApiProperty()
  @IsInt()
  @IsNotEmpty()
  id: number;
}
