import { ApiProperty } from '@nestjs/swagger';
import { User } from '@/users/domain/user';
import { Division } from '@/masters/divisions/domain/division';
import { Department } from '@/masters/departments/domain/department';
import { Section } from '@/masters/sections/domain/section';
import { SubSection } from '@/masters/sub-sections/domain/sub-section';
import { Exclude } from 'class-transformer';
import { Causer } from '@/utils/domain/causer';
import { StatusEnum } from '@/utils/enums/status-enum';

/**
 * Domain entity representing a cost center in the organizational hierarchy.
 *
 * A cost center is a financial accounting unit that tracks costs and revenues
 * for specific organizational units. Cost centers are automatically generated
 * based on the organizational structure (division, department, section, sub-section)
 * and follow a hierarchical code system.
 *
 * The cost center code is generated by concatenating the codes of the associated
 * organizational entities: division + department + section + sub_section.
 *
 * @version 3
 * @since 1.0.0
 * @author Masters Module Team
 *
 * @example
 * ```typescript
 * const costCenter: CostCenter = {
 *   id: 1,
 *   cost_center_code: '01010101',
 *   cost_center_name: '01010101 / Backend',
 *   division: { id: 1, division_code: '01', division_name: 'CODY' },
 *   department: { id: 1, department_code: '01', department_name: 'Operation' },
 *   section: { id: 1, section_code: '01', section_name: 'SD1' },
 *   sub_section: { id: 1, sub_section_code: '01', sub_section_name: 'Backend' },
 *   remarks: 'Backend Development Team',
 *   status: StatusEnum.ACTIVE,
 *   created_by: { id: 1, first_name: 'John', last_name: 'Doe' },
 *   created_at: new Date(),
 *   updated_by: { id: 1, first_name: 'John', last_name: 'Doe' },
 *   updated_at: new Date()
 * };
 * ```
 */
export class CostCenter {
  /** Unique identifier for the cost center */
  @ApiProperty({
    type: Number,
    example: 1,
  })
  id: number;

  /** Unique cost center code generated from related entities */
  @ApiProperty({
    type: String,
    example: '01010101',
  })
  cost_center_code: string;

  /** Human-readable name of the cost center */
  @ApiProperty({
    type: String,
    example: '01010101 / Backend',
  })
  cost_center_name?: string;

  /** Associated division entity */
  @ApiProperty({
    type: () => Division,
    example: { id: 1, division_code: '01', division_name: 'CODY' },
  })
  division: Pick<Division, 'id' | 'division_code' | 'division_name'> | null;

  /** Associated department entity (optional) */
  @ApiProperty({
    type: () => Department,
    example: { id: 1, department_code: '01', department_name: 'Operation' },
  })
  department: Pick<
    Department,
    'id' | 'department_code' | 'department_name'
  > | null;

  /** Associated section entity (optional) */
  @ApiProperty({
    type: () => Section,
    example: { id: 1, section_code: '01', section_name: 'SD1' },
  })
  section: Pick<Section, 'id' | 'section_code' | 'section_name'> | null;

  /** Associated sub-section entity (optional) */
  @ApiProperty({
    type: () => SubSection,
    example: { id: 1, sub_section_code: '01', sub_section_name: 'Backend' },
  })
  sub_section: Pick<
    SubSection,
    'id' | 'sub_section_code' | 'sub_section_name'
  > | null;

  /** Additional remarks or description for the cost center */
  @ApiProperty({
    type: String,
    example: 'To be used by SD1 Backend Engineers',
  })
  remarks: string | null;

  /** Current status of the cost center (Active, Hold, Cancelled) */
  @ApiProperty({
    type: String,
    nullable: false,
    example: StatusEnum.ACTIVE,
  })
  status: string;

  /** User who created the cost center */
  @ApiProperty({
    type: () => User,
    nullable: false,
    example: { id: 1, first_name: 'John', last_name: 'Doe' },
  })
  created_by: Causer;

  /** Timestamp when the cost center was created */
  @ApiProperty()
  created_at: Date;

  /** User who last updated the cost center */
  @ApiProperty({
    type: () => User,
    nullable: false,
    example: { id: 1, first_name: 'John', last_name: 'Doe' },
  })
  updated_by: Causer;

  /** Timestamp when the cost center was last updated */
  @ApiProperty()
  updated_at: Date;

  /** User who deleted the cost center (if soft deleted) */
  @ApiProperty({
    type: () => User,
    nullable: true,
    example: null,
  })
  deleted_by?: Causer | null;

  /** Timestamp when the cost center was deleted (if soft deleted) */
  @ApiProperty({
    example: null,
  })
  deleted_at?: Date | null;

  @Exclude()
  __entity?: string;
}
