import {
  CreateDateColumn,
  Entity,
  UpdateDateColumn,
  DeleteDateColumn,
  Column,
  ManyToOne,
  JoinColumn,
  PrimaryGeneratedColumn,
  Unique,
} from 'typeorm';
import { EntityHelper } from '@/utils/entity-helper';
import { UserEntity } from '@/users/persistence/entities/user.entity';
import { StatusEnum } from '@/utils/enums/status-enum';

/**
 * TypeORM entity representing a sub-section in the database.
 *
 * This entity defines the database structure for sub-sections, including
 * all necessary fields, relationships, and constraints. It extends
 * EntityHelper for common audit functionality and includes relationships
 * with user entities.
 *
 * The entity includes database-specific features such as:
 * - Unique constraints for business keys
 * - Foreign key relationships with proper joins
 * - Soft delete functionality with audit trails
 * - Status management with enum constraints
 * - Automatic timestamp management
 *
 * @version 3
 * @since 1.0.0
 * @author Masters Module Team
 */
@Entity({
  name: 'sub_section',
})
@Unique(['sub_section_code'])
export class SubSectionEntity extends EntityHelper {
  /**
   * Unique identifier for the sub-section.
   *
   * This field serves as the primary key for the sub-section and is
   * automatically generated by the database. It uniquely identifies
   * each sub-section in the system.
   *
   * @example 1
   * @example 123
   */
  @PrimaryGeneratedColumn()
  id: number;

  /**
   * Unique business code for the sub-section.
   *
   * This field represents the human-readable business code for the sub-section.
   * It must be unique across all sub-sections and follows a specific format.
   * The code is used for business operations and reporting.
   *
   * @example '00'
   * @example '01'
   * @example '99'
   */
  @Column({
    type: 'char',
    length: 2,
    unique: true,
    nullable: false,
  })
  sub_section_code: string;

  /**
   * Human-readable name of the sub-section.
   *
   * This field contains the display name for the sub-section used in
   * user interfaces and reports. It should be descriptive and
   * clearly identify the sub-section's purpose or function.
   *
   * @example 'Backend'
   * @example 'Frontend'
   * @example 'DevOps'
   */
  @Column({
    type: String,
    length: 100,
    nullable: false,
  })
  sub_section_name: string;

  /**
   * The user who serves as the head of the sub-section.
   *
   * This field represents the person responsible for leading the sub-section.
   * It establishes a many-to-one relationship with the UserEntity and
   * includes eager loading for performance optimization.
   *
   * @example UserEntity with id: 1, first_name: 'John', last_name: 'Doe'
   */
  @ManyToOne(() => UserEntity, { eager: true, nullable: false })
  @JoinColumn({ name: 'sub_section_head' })
  sub_section_head: UserEntity;

  /**
   * Current status of the sub-section.
   *
   * This field indicates the operational status of the sub-section.
   * Valid values include Active, Hold, and Cancelled. The status
   * determines whether the sub-section is operational and available
   * for business processes.
   *
   * @example StatusEnum.ACTIVE
   * @example StatusEnum.HOLD
   * @example StatusEnum.CANCELLED
   */
  @Column({
    type: 'enum',
    enum: StatusEnum,
    default: StatusEnum.ACTIVE,
    nullable: false,
  })
  status: StatusEnum;

  /**
   * The user who created the sub-section.
   *
   * This field tracks the user responsible for creating the sub-section.
   * It establishes a many-to-one relationship with the UserEntity and
   * includes eager loading for performance optimization.
   *
   * @example UserEntity with id: 1, first_name: 'John', last_name: 'Doe'
   */
  @ManyToOne(() => UserEntity, { eager: true, nullable: false })
  @JoinColumn({ name: 'created_by' })
  created_by: UserEntity;

  /**
   * Timestamp when the sub-section was created.
   *
   * This field records the exact date and time when the sub-section
   * was first created in the system. It's automatically set by
   * the database and used for audit trails and reporting.
   *
   * @example new Date('2024-01-15T10:30:00Z')
   */
  @CreateDateColumn()
  created_at: Date;

  /**
   * The user who last updated the sub-section.
   *
   * This field tracks the user responsible for the most recent update
   * to the sub-section. It establishes a many-to-one relationship with
   * the UserEntity and includes eager loading for performance optimization.
   *
   * @example UserEntity with id: 1, first_name: 'John', last_name: 'Doe'
   */
  @ManyToOne(() => UserEntity, { eager: true, nullable: false })
  @JoinColumn({ name: 'updated_by' })
  updated_by: UserEntity;

  /**
   * Timestamp when the sub-section was last updated.
   *
   * This field records the exact date and time when the sub-section
   * was most recently modified. It's automatically updated by
   * the database and used for audit trails and change tracking.
   *
   * @example new Date('2024-01-20T14:45:00Z')
   */
  @UpdateDateColumn()
  updated_at: Date;

  /**
   * The user who deleted the sub-section.
   *
   * This field tracks the user responsible for deleting the sub-section.
   * It's only populated when the sub-section is soft deleted and
   * includes eager loading for performance optimization.
   *
   * @example null
   * @example UserEntity with id: 1, first_name: 'John', last_name: 'Doe'
   */
  @ManyToOne(() => UserEntity, { eager: true, nullable: true })
  @JoinColumn({ name: 'deleted_by' })
  deleted_by?: UserEntity | null;

  /**
   * Timestamp when the sub-section was deleted.
   *
   * This field records the exact date and time when the sub-section
   * was soft deleted. It's only populated when the sub-section is
   * deleted and used for audit trails and data recovery purposes.
   *
   * @example null
   * @example new Date('2024-01-25T16:30:00Z')
   */
  @DeleteDateColumn()
  deleted_at?: Date | null;
}
