import {
  CreateDateColumn,
  Entity,
  UpdateDateColumn,
  DeleteDateColumn,
  Column,
  ManyToOne,
  JoinColumn,
  PrimaryGeneratedColumn,
  Unique,
} from 'typeorm';
import { EntityHelper } from '@/utils/entity-helper';
import { UserEntity } from '@/users/persistence/entities/user.entity';
import { StatusEnum } from '@/utils/enums/status-enum';

/**
 * TypeORM entity representing a section in the database.
 *
 * This entity defines the database structure for sections, including
 * all necessary fields, relationships, and constraints. It extends
 * EntityHelper for common audit functionality and includes relationships
 * with user entities for section head and audit tracking.
 *
 * The entity includes database-specific features such as:
 * - Unique constraints for business keys (section_code)
 * - Foreign key relationships with proper joins
 * - Soft delete functionality with audit trails
 * - Status management with enum constraints
 * - Automatic timestamp management
 *
 * @version 3
 * @since 1.0.0
 * @author Masters Module Team
 *
 * @example
 * ```typescript
 * const entity = new SectionEntity();
 * entity.section_code = '01';
 * entity.section_name = 'Engineering';
 * entity.section_head = userEntity;
 * ```
 */
@Entity({
  name: 'section',
})
@Unique(['section_code'])
export class SectionEntity extends EntityHelper {
  /**
   * Unique identifier for the section.
   *
   * This field serves as the primary key for the section entity
   * and is automatically generated by the database.
   *
   * @example 1
   * @example 123
   */
  @PrimaryGeneratedColumn()
  id: number;

  /**
   * Unique business code for the section.
   *
   * This field represents the human-readable business code for the section.
   * It must be unique across all sections and follows a specific format.
   * The code is used for business operations and reporting.
   *
   * @example '00'
   * @example '01'
   * @example '99'
   */
  @Column({
    type: 'char',
    length: 2,
    unique: true,
    nullable: false,
  })
  section_code: string;

  /**
   * Human-readable name of the section.
   *
   * This field contains the display name for the section used in
   * user interfaces and reports. It should be descriptive and
   * clearly identify the section's purpose or function.
   *
   * @example 'Engineering'
   * @example 'Marketing'
   * @example 'Sales'
   */
  @Column({
    type: String,
    length: 100,
    nullable: false,
  })
  section_name: string;

  /**
   * The user who serves as the head of the section.
   *
   * This field represents the person responsible for leading the section.
   * It establishes a many-to-one relationship with the UserEntity and
   * includes eager loading for performance optimization.
   *
   * @example UserEntity with id: 1, first_name: 'John', last_name: 'Doe'
   */
  @ManyToOne(() => UserEntity, { eager: true, nullable: false })
  @JoinColumn({ name: 'section_head' })
  section_head: UserEntity;

  /**
   * Current status of the section.
   *
   * This field indicates the operational status of the section.
   * Valid values include Active, Hold, and Cancelled. The status
   * determines whether the section is operational and available
   * for business processes.
   *
   * @example StatusEnum.ACTIVE
   * @example StatusEnum.HOLD
   * @example StatusEnum.CANCELLED
   */
  @Column({
    type: 'enum',
    enum: StatusEnum,
    default: StatusEnum.ACTIVE,
    nullable: false,
  })
  status: StatusEnum;

  /**
   * User who created the section.
   *
   * This field tracks the user who originally created the section.
   * It establishes a many-to-one relationship with the UserEntity and
   * includes eager loading for audit purposes.
   *
   * @example UserEntity with id: 1, first_name: 'John', last_name: 'Doe'
   */
  @ManyToOne(() => UserEntity, { eager: true, nullable: false })
  @JoinColumn({ name: 'created_by' })
  created_by: UserEntity;

  /**
   * Timestamp when the section was created.
   *
   * This field records the exact date and time when the section
   * was first created in the system. It's automatically managed
   * by TypeORM and used for audit purposes.
   *
   * @example "2024-01-15T10:30:00.000Z"
   */
  @CreateDateColumn()
  created_at: Date;

  /**
   * User who last updated the section.
   *
   * This field tracks the user who made the most recent changes
   * to the section. It establishes a many-to-one relationship
   * with the UserEntity and includes eager loading for audit purposes.
   *
   * @example UserEntity with id: 1, first_name: 'John', last_name: 'Doe'
   */
  @ManyToOne(() => UserEntity, { eager: true, nullable: false })
  @JoinColumn({ name: 'updated_by' })
  updated_by: UserEntity;

  /**
   * Timestamp when the section was last updated.
   *
   * This field records the exact date and time when the section
   * was last modified. It's automatically managed by TypeORM
   * and used for audit purposes and change tracking.
   *
   * @example "2024-01-15T14:30:00.000Z"
   */
  @UpdateDateColumn()
  updated_at: Date;

  /**
   * User who deleted the section (if applicable).
   *
   * This field tracks the user who performed the soft delete operation
   * on the section. It's null for active sections and contains user
   * information for deleted sections. Includes eager loading for audit purposes.
   *
   * @example null
   * @example UserEntity with id: 1, first_name: 'John', last_name: 'Doe'
   */
  @ManyToOne(() => UserEntity, { eager: true, nullable: true })
  @JoinColumn({ name: 'deleted_by' })
  deleted_by?: UserEntity | null;

  /**
   * Timestamp when the section was deleted (if applicable).
   *
   * This field records the exact date and time when the section
   * was soft deleted. It's null for active sections and contains
   * the deletion timestamp for deleted sections. Automatically
   * managed by TypeORM for soft delete functionality.
   *
   * @example null
   * @example "2024-01-15T16:30:00.000Z"
   */
  @DeleteDateColumn()
  deleted_at?: Date | null;
}
