import { ApiProperty } from '@nestjs/swagger';
import { User } from '@/users/domain/user';
import { Exclude } from 'class-transformer';
import { StatusEnum } from '@/users/users.enum';
import { Causer } from '@/utils/domain/causer';

/**
 * Domain entity representing a department in the organizational hierarchy.
 *
 * This domain entity represents a complete department with all its properties,
 * relationships, and audit information. It serves as the primary business
 * object for department operations and includes all necessary fields for
 * comprehensive department management.
 *
 * @version 3
 * @since 1.0.0
 * @author Masters Module Team
 *
 * @example
 * ```typescript
 * // Create a new department
 * const department = new Department();
 * department.department_code = '01';
 * department.department_name = 'Information Technology';
 * department.department_head = userEntity;
 * department.status = StatusEnum.ACTIVE;
 *
 * // Get department details
 * const department: Department = await this.departmentsService.findById(1);
 * // Returns: { id: 1, department_code: '01', department_name: 'Information Technology', ... }
 * ```
 */
export class Department {
  /**
   * Unique identifier of the department.
   *
   * The primary key that uniquely identifies a department in the system.
   * Auto-generated by the database and used for all department operations.
   *
   * @example 1
   * @example 5
   * @example 10
   */
  @ApiProperty({
    type: Number,
    example: 1,
  })
  id: number;

  /**
   * Unique department code identifier.
   *
   * A 2-character code that uniquely identifies the department.
   * Must be unique across all departments and follows the pattern
   * of numbers between 00 and 99. Used for system identification.
   *
   * @example "01"
   * @example "99"
   * @example "00"
   */
  @ApiProperty({
    type: String,
    nullable: false,
    example: '00',
  })
  department_code: string;

  /**
   * Human-readable name of the department.
   *
   * The full name of the department, used for display purposes
   * and in user interfaces. This is the primary identifier users
   * will see and interact with.
   *
   * @example "Information Technology"
   * @example "Human Resources"
   * @example "Finance"
   */
  @ApiProperty({
    type: String,
    nullable: false,
    example: 'Back Office',
  })
  department_name: string;

  /**
   * User who serves as the department head.
   *
   * Reference to the user who is designated as the head of this department.
   * Contains essential user information needed for department management
   * and display purposes.
   *
   * @example { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' }
   */
  @ApiProperty({
    type: () => User,
    nullable: false,
    example: { id: 1, first_name: 'John', last_name: 'Doe', cost_center: '00' },
  })
  department_head: Pick<
    User,
    'id' | 'first_name' | 'last_name' | 'cost_center'
  >;

  /**
   * Current status of the department.
   *
   * Indicates whether the department is active, on hold, or cancelled.
   * Controls the department's availability for use in the system
   * and affects its visibility in various operations.
   *
   * @example StatusEnum.ACTIVE
   * @example StatusEnum.HOLD
   * @example StatusEnum.CANCELLED
   */
  @ApiProperty({
    type: String,
    nullable: false,
    example: StatusEnum.ACTIVE,
  })
  status: string;

  /**
   * User who created this department record.
   *
   * Reference to the user who originally created this department.
   * Contains essential user information for audit purposes and
   * tracking who created the department.
   *
   * @example { id: 1, first_name: 'John', last_name: 'Doe' }
   */
  @ApiProperty({
    type: () => User,
    nullable: false,
    example: { id: 1, first_name: 'John', last_name: 'Doe' },
  })
  created_by: Causer;

  /**
   * Timestamp when the department was created.
   *
   * Automatically set when the department record is first created.
   * Used for audit purposes and tracking when the department
   * was added to the system.
   *
   * @example "2024-01-15T10:30:00.000Z"
   */
  @ApiProperty()
  created_at: Date;

  /**
   * User who last updated this department record.
   *
   * Reference to the user who most recently modified this department.
   * Contains essential user information for audit purposes and
   * tracking who last updated the department.
   *
   * @example { id: 2, first_name: 'Jane', last_name: 'Smith' }
   */
  @ApiProperty({
    type: () => User,
    nullable: false,
    example: { id: 1, first_name: 'John', last_name: 'Doe' },
  })
  updated_by: Causer;

  /**
   * Timestamp when the department was last updated.
   *
   * Automatically updated whenever the department record is modified.
   * Used for audit purposes and tracking when the department
   * was last changed.
   *
   * @example "2024-01-20T14:45:00.000Z"
   */
  @ApiProperty()
  updated_at: Date;

  /**
   * User who deleted this department record.
   *
   * Reference to the user who performed the soft delete operation.
   * This field is nullable and is only set when the department is soft deleted.
   * Contains essential user information for audit purposes.
   *
   * @example { id: 3, first_name: 'Bob', last_name: 'Johnson' } or null
   */
  @ApiProperty({
    type: () => User,
    nullable: true,
    example: null,
  })
  deleted_by?: Causer | null;

  /**
   * Timestamp when the department was soft deleted.
   *
   * Automatically set when the department record is soft deleted.
   * This field is nullable and is only set when the department is soft deleted.
   * Used for audit purposes and tracking when the department was removed.
   *
   * @example "2024-01-25T09:15:00.000Z" or null
   */
  @ApiProperty({
    example: null,
  })
  deleted_at?: Date | null;

  /**
   * Internal entity identifier (excluded from serialization).
   *
   * This field is used internally by the system for entity tracking
   * and is excluded from API responses to keep the interface clean.
   * It should not be used in client applications.
   *
   * @private
   */
  @Exclude()
  __entity?: string;
}
