export interface EkumpraVariantAttribute {
  name: string;
  value: string;
}

export interface EkumpraVariantData {
  variantName: string;
  variantDescription: string;
  variantSku: string;
  variantCostPrice: number;
  variantSellingPrice: number;
  variantStatus: string;
  variantMinimumOrder: number;
  attributes: EkumpraVariantAttribute[];
}

export interface EkumpraProductData {
  productName: string;
  productDescription: string;
  productStatus: string;
  categoryName: string;
  variants: EkumpraVariantData[];
}

export const EKUMPRA_PRODUCTS: EkumpraProductData[] = [
  {
    productName: 'Powder',
    productDescription: 'DPO Powder Products',
    productStatus: 'Published',
    categoryName: 'POWDER',
    variants: [
      {
        variantName: 'Powder Cafe Mocha',
        variantDescription: 'DPO Powder Cafe Mocha',
        variantSku: 'PW-CAFMOC',
        variantCostPrice: 210,
        variantSellingPrice: 327.89,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Cafe Mocha' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Caramel',
        variantDescription: 'DPO Powder Caramel',
        variantSku: 'PW-CARAML',
        variantCostPrice: 173,
        variantSellingPrice: 268.27,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Caramel' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Cookies and Cream',
        variantDescription: 'DPO Powder Cookies and Cream',
        variantSku: 'PW-COOCRE',
        variantCostPrice: 187,
        variantSellingPrice: 253,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Cookies and Cream' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Cream Cheese',
        variantDescription: 'DPO Powder Cream Cheese',
        variantSku: 'PW-CRMCHE',
        variantCostPrice: 310,
        variantSellingPrice: 427,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Cream Cheese' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Creamy milk',
        variantDescription: 'DPO Powder Creamy milk',
        variantSku: 'PW-CREMLK',
        variantCostPrice: 165,
        variantSellingPrice: 244.4,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Creamy Milk' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Cucumber Lemonade',
        variantDescription: 'DPO Powder Cucumber Lemonade',
        variantSku: 'PW-CUMBERLEMNADE',
        variantCostPrice: 1011,
        variantSellingPrice: 1075,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Cucumber Lemonade' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Dark Chocolate',
        variantDescription: 'DPO Powder Dark Chocolate',
        variantSku: 'PW-DRKCHO',
        variantCostPrice: 222,
        variantSellingPrice: 379.07,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Dark Chocolate' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Hokkaido',
        variantDescription: 'DPO Powder Hokkaido',
        variantSku: 'PW-HOKKDO',
        variantCostPrice: 212,
        variantSellingPrice: 284.97,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Hokkaido' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Mango',
        variantDescription: 'DPO Powder Mango',
        variantSku: 'PW-MANGO',
        variantCostPrice: 167,
        variantSellingPrice: 207,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Mango' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Mango Yogurt',
        variantDescription: 'DPO Powder Mango Yogurt',
        variantSku: 'PW-MNGYOG',
        variantCostPrice: 522,
        variantSellingPrice: 630,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Mango Yogurt' },
          { name: 'Weight', value: '1.5kg' },
        ],
      },
      {
        variantName: 'Powder Matcha',
        variantDescription: 'DPO Powder Matcha',
        variantSku: 'PW-MATCHA',
        variantCostPrice: 244,
        variantSellingPrice: 345.97,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Matcha' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Milktea',
        variantDescription: 'DPO Powder Milktea',
        variantSku: 'PW-MLKTEA',
        variantCostPrice: 185,
        variantSellingPrice: 249.1,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Milktea' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Okinawa',
        variantDescription: 'DPO Powder Okinawa',
        variantSku: 'PW-OKINWA',
        variantCostPrice: 217,
        variantSellingPrice: 299.46,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Okinawa' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Red Velvet',
        variantDescription: 'DPO Powder Red Velvet',
        variantSku: 'PW-RDVELV',
        variantCostPrice: 189,
        variantSellingPrice: 260.82,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Red Velvet' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Strawberry',
        variantDescription: 'DPO Powder Strawberry',
        variantSku: 'PW-STWBRY',
        variantCostPrice: 167,
        variantSellingPrice: 245.64,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Strawberry' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Strawberry Yogurt',
        variantDescription: 'DPO Powder Strawberry Yogurt',
        variantSku: 'PW-SBRYYOG',
        variantCostPrice: 532,
        variantSellingPrice: 630,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Strawberry Yogurt' },
          { name: 'Weight', value: '1.5kg' },
        ],
      },
      {
        variantName: 'Powder Tableya',
        variantDescription: 'DPO Powder Tableya',
        variantSku: 'PW-TABLYA',
        variantCostPrice: 210,
        variantSellingPrice: 348.43,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Tableya' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Ube Taro',
        variantDescription: 'DPO Powder Ube Taro',
        variantSku: 'PW-UBETAR',
        variantCostPrice: 170,
        variantSellingPrice: 234.06,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Ube Taro' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Vanilla',
        variantDescription: 'DPO Powder Vanilla',
        variantSku: 'PW-VANILA',
        variantCostPrice: 170,
        variantSellingPrice: 230,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Vanilla' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Whipped Cream',
        variantDescription: 'DPO Powder Whipped Cream',
        variantSku: 'PW-WHPCRE',
        variantCostPrice: 162,
        variantSellingPrice: 197.8,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Whipped Cream' },
          { name: 'Weight', value: '500g' },
        ],
      },
      {
        variantName: 'Powder White Chocolate',
        variantDescription: 'DPO Powder White Chocolate',
        variantSku: 'PW-WHTCHO',
        variantCostPrice: 208,
        variantSellingPrice: 248.4,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'White Chocolate' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Wintermelon',
        variantDescription: 'DPO Powder Wintermelon',
        variantSku: 'PW-WINMLN',
        variantCostPrice: 236,
        variantSellingPrice: 299,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Wintermelon' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Powder Yogurt Plain',
        variantDescription: 'DPO Powder Yogurt Plain',
        variantSku: 'PW-PLNYOG',
        variantCostPrice: 643,
        variantSellingPrice: 700,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Yogurt Plain' },
          { name: 'Weight', value: '1.5kg' },
        ],
      },
    ],
  },
  {
    productName: 'Cup Paper',
    productDescription: 'DPO Cup Paper Products',
    productStatus: 'Published',
    categoryName: 'PAPER PRODUCT',
    variants: [
      {
        variantName: 'Cup Paper DW Black 12OZ-Plain 25pcs',
        variantDescription: 'DPO Cup Paper DW Black 12OZ-Plain 25pcs',
        variantSku: 'PR-CPBLKPN-12',
        variantCostPrice: 200,
        variantSellingPrice: 300,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Color', value: 'Black' },
          { name: 'Volume', value: '12OZ' },
          { name: 'Style', value: 'Plain' },
          { name: 'Quantity', value: '25pcs' },
        ],
      },
      {
        variantName: 'Cup Paper DW Black 16OZ-Everyday 25 pcs',
        variantDescription: 'DPO Cup Paper DW Black 16OZ-Everyday 25 pcs',
        variantSku: 'PR-CUPPAPECAT-16',
        variantCostPrice: 200,
        variantSellingPrice: 250,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Color', value: 'Black' },
          { name: 'Volume', value: '16OZ' },
          { name: 'Style', value: 'Everyday' },
          { name: 'Quantity', value: '25pcs' },
        ],
      },
      {
        variantName: 'Cup Paper DW Black 16OZ-Plain 25pcs',
        variantDescription: 'DPO Cup Paper DW Black 16OZ-Plain 25pcs',
        variantSku: 'PR-CPBLKPN-16',
        variantCostPrice: 122.5,
        variantSellingPrice: 155,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Color', value: 'Black' },
          { name: 'Volume', value: '16OZ' },
          { name: 'Style', value: 'Plain' },
          { name: 'Quantity', value: '25pcs' },
        ],
      },
      {
        variantName: 'Cup Paper DW Black 16OZ-UB 25pcs',
        variantDescription: 'DPO Cup Paper DW Black 16OZ-UB 25pcs',
        variantSku: 'PR-UBCPBLK-16',
        variantCostPrice: 122.5,
        variantSellingPrice: 162.5,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Color', value: 'Black' },
          { name: 'Volume', value: '16OZ' },
          { name: 'Style', value: 'UB' },
          { name: 'Quantity', value: '25pcs' },
        ],
      },
      {
        variantName: 'Cup Paper DW Black 8OZ-Plain 25pcs',
        variantDescription: 'DPO Cup Paper DW Black 8OZ-Plain 25pcs',
        variantSku: 'PR-CPBBLKPN-8',
        variantCostPrice: 175,
        variantSellingPrice: 250,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Color', value: 'Black' },
          { name: 'Volume', value: '8OZ' },
          { name: 'Style', value: 'Plain' },
          { name: 'Quantity', value: '25pcs' },
        ],
      },
      {
        variantName: 'Cup Paper DW Black W/ LIDS 12OZ-Everyday 50pcs',
        variantDescription:
          'DPO Cup Paper DW Black W/ LIDS 12OZ-Everyday 50pcs',
        variantSku: 'PR-CUPPAPECAT-12',
        variantCostPrice: 460.5,
        variantSellingPrice: 575,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Color', value: 'Black' },
          { name: 'Volume', value: '12OZ' },
          { name: 'Style', value: 'Everyday with Lids' },
          { name: 'Quantity', value: '50pcs' },
        ],
      },
      {
        variantName: 'Cup Paper DW Black W/LIDS 8OZ-Everyday 50pcs',
        variantDescription: 'DPO Cup Paper DW Black W/LIDS 8OZ-Everyday 50pcs',
        variantSku: 'PR-CUPPAPECAT-8',
        variantCostPrice: 412,
        variantSellingPrice: 500,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Color', value: 'Black' },
          { name: 'Volume', value: '8OZ' },
          { name: 'Style', value: 'Everyday with Lids' },
          { name: 'Quantity', value: '50pcs' },
        ],
      },
      {
        variantName: 'Cup Paper White 16OZ-Plain 50 pcs',
        variantDescription: 'DPO Cup Paper White 16OZ-Plain 50 pcs',
        variantSku: 'PR-CPPERWHI-16',
        variantCostPrice: 82.5,
        variantSellingPrice: 155,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Color', value: 'White' },
          { name: 'Volume', value: '16OZ' },
          { name: 'Style', value: 'Plain' },
          { name: 'Quantity', value: '50pcs' },
        ],
      },
      {
        variantName: 'Cup Paper White 22OZ-Plain 50 pcs',
        variantDescription: 'DPO Cup Paper White 22OZ-Plain 50 pcs',
        variantSku: 'PR-CPPERWHI-22',
        variantCostPrice: 156,
        variantSellingPrice: 260,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Color', value: 'White' },
          { name: 'Volume', value: '22OZ' },
          { name: 'Style', value: 'Plain' },
          { name: 'Quantity', value: '50pcs' },
        ],
      },
    ],
  },
  {
    productName: 'Cup PET',
    productDescription: 'DPO Cup PET Products',
    productStatus: 'Published',
    categoryName: 'PLASTIC PRODUCT',
    variants: [
      {
        variantName: 'Cup-Pet Cone Shape Sundae 8oz-SCC 50pcs',
        variantDescription: 'DPO Cup-Pet Cone Shape Sundae 8oz-SCC 50pcs',
        variantSku: 'PL-CUPPETSCC-8',
        variantCostPrice: 65,
        variantSellingPrice: 149.5,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Shape', value: 'Cone' },
          { name: 'Volume', value: '8oz' },
          { name: 'Style', value: 'SCC' },
          { name: 'Quantity', value: '50pcs' },
        ],
      },
      {
        variantName: 'Cup-PET Sundae 9oz-UB',
        variantDescription: 'DPO Cup-PET Sundae 9oz-UB',
        variantSku: 'PL-CUPPETUB-8',
        variantCostPrice: 65,
        variantSellingPrice: 149.5,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Shape', value: 'Sundae' },
          { name: 'Volume', value: '9oz' },
          { name: 'Style', value: 'UB' },
          { name: 'Quantity', value: '50pcs' },
        ],
      },
      {
        variantName: 'Cup PET 1L-UB 25 pcs',
        variantDescription: 'DPO Cup PET 1L-UB 25 pcs',
        variantSku: 'PL-CUPPETUB-1L',
        variantCostPrice: 115,
        variantSellingPrice: 175,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Volume', value: '1L' },
          { name: 'Style', value: 'UB' },
          { name: 'Quantity', value: '25pcs' },
        ],
      },
      {
        variantName: 'Cup PET 22OZ-UB 50 pcs',
        variantDescription: 'DPO Cup PET 22OZ-UB 50 pcs',
        variantSku: 'PL-CUPPETUB-22',
        variantCostPrice: 110,
        variantSellingPrice: 232.5,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Volume', value: '22OZ' },
          { name: 'Style', value: 'UB' },
          { name: 'Quantity', value: '50pcs' },
        ],
      },
      {
        variantName: 'Cup PET 16OZ-UB 50 pcs',
        variantDescription: 'DPO Cup PET 16OZ-UB 50 pcs',
        variantSku: 'PL-CUPPETUB-16',
        variantCostPrice: 95,
        variantSellingPrice: 199.5,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Volume', value: '16OZ' },
          { name: 'Style', value: 'UB' },
          { name: 'Quantity', value: '50pcs' },
        ],
      },
      {
        variantName: 'Cup PET 1L-SCC 25 pcs',
        variantDescription: 'DPO Cup PET 1L-SCC 25 pcs',
        variantSku: 'PL-CUPPETSCC-1L',
        variantCostPrice: 115,
        variantSellingPrice: 175,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Volume', value: '1L' },
          { name: 'Style', value: 'SCC' },
          { name: 'Quantity', value: '25pcs' },
        ],
      },
      {
        variantName: 'Cup PET 22OZ-EVERYDAY 50 pcs',
        variantDescription: 'DPO Cup PET 22OZ-EVERYDAY 50 pcs',
        variantSku: 'PL-CUPPETECAT-22',
        variantCostPrice: 197.5,
        variantSellingPrice: 225,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Volume', value: '22OZ' },
          { name: 'Style', value: 'Everyday' },
          { name: 'Quantity', value: '50pcs' },
        ],
      },
      {
        variantName: 'Cup PET 22OZ-SCC 50 pcs',
        variantDescription: 'DPO Cup PET 22OZ-SCC 50 pcs',
        variantSku: 'PL-CUPPETSCC-22',
        variantCostPrice: 110,
        variantSellingPrice: 232.5,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Volume', value: '22OZ' },
          { name: 'Style', value: 'SCC' },
          { name: 'Quantity', value: '50pcs' },
        ],
      },
      {
        variantName: 'Cup PET 16OZ-EVERYDAY 50pcs',
        variantDescription: 'DPO Cup PET 16OZ-EVERYDAY 50pcs',
        variantSku: 'PL-CUPPETECAT-16',
        variantCostPrice: 175,
        variantSellingPrice: 215,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Volume', value: '16OZ' },
          { name: 'Style', value: 'Everyday' },
          { name: 'Quantity', value: '50pcs' },
        ],
      },
      {
        variantName: 'Cup PET 16OZ-SCC 50 pcs',
        variantDescription: 'DPO Cup PET 16OZ-SCC 50 pcs',
        variantSku: 'PL-CUPPETSCC-16',
        variantCostPrice: 95,
        variantSellingPrice: 199.5,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Volume', value: '16OZ' },
          { name: 'Style', value: 'SCC' },
          { name: 'Quantity', value: '50pcs' },
        ],
      },
    ],
  },
  {
    productName: 'Lid Flat',
    productDescription: 'DPO Lid Flat Products',
    productStatus: 'Published',
    categoryName: 'PLASTIC PRODUCT',
    variants: [
      {
        variantName: 'Lid Flat 1L 50pcs',
        variantDescription: 'DPO Lid Flat 1L 50pcs',
        variantSku: 'PL-LDFLT1L-50',
        variantCostPrice: 65,
        variantSellingPrice: 100,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Size', value: '1L' },
          { name: 'Quantity', value: '50pcs' },
        ],
      },
      {
        variantName: 'Lid Flat 95mm 100pcs',
        variantDescription: 'DPO Lid Flat 95mm 100pcs',
        variantSku: 'PL-LIDFLT-95',
        variantCostPrice: 65,
        variantSellingPrice: 100,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Size', value: '95mm' },
          { name: 'Quantity', value: '100pcs' },
        ],
      },
    ],
  },
  {
    productName: 'Spoon',
    productDescription: 'DPO Spoon Products',
    productStatus: 'Published',
    categoryName: 'PLASTIC PRODUCT',
    variants: [
      {
        variantName: 'Spoon Black-Teardrop 100pcs',
        variantDescription: 'DPO Spoon Black-Teardrop 100pcs',
        variantSku: 'PL-SPOBLKFRP-100',
        variantCostPrice: 400,
        variantSellingPrice: 450,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Color', value: 'Black' },
          { name: 'Style', value: 'Teardrop' },
          { name: 'Quantity', value: '100pcs' },
        ],
      },
      {
        variantName: 'Ice Cream Spoon',
        variantDescription: 'DPO Ice Cream Spoon',
        variantSku: 'PL-ICESPO',
        variantCostPrice: 25,
        variantSellingPrice: 55,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Style', value: 'Ice Cream' }],
      },
    ],
  },
  {
    productName: 'Straw Boba',
    productDescription: 'DPO Straw Boba Products',
    productStatus: 'Published',
    categoryName: 'PLASTIC PRODUCT',
    variants: [
      {
        variantName: 'Straw Boba Paper-Plain 100pcs',
        variantDescription: 'DPO Straw Boba Paper-Plain 100pcs',
        variantSku: 'PR-STRBPLN-100',
        variantCostPrice: 135,
        variantSellingPrice: 200,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Material', value: 'Paper' },
          { name: 'Style', value: 'Plain' },
          { name: 'Quantity', value: '100pcs' },
        ],
      },
      {
        variantName: 'Straw Boba Plastic-Plain 100pcs',
        variantDescription: 'DPO Straw Boba Plastic-Plain 100pcs',
        variantSku: 'PL-STRBOBP-100',
        variantCostPrice: 45,
        variantSellingPrice: 80,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Material', value: 'Plastic' },
          { name: 'Style', value: 'Plain' },
          { name: 'Quantity', value: '100pcs' },
        ],
      },
      {
        variantName: 'Straw Boba Plastic-SCC 100pcs',
        variantDescription: 'DPO Straw Boba Plastic-SCC 100pcs',
        variantSku: 'PL-SCCSTRP-100',
        variantCostPrice: 50,
        variantSellingPrice: 99,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Material', value: 'Plastic' },
          { name: 'Style', value: 'SCC' },
          { name: 'Quantity', value: '100pcs' },
        ],
      },
      {
        variantName: 'Straw Boba Plastic-UB 100pcs',
        variantDescription: 'DPO Straw Boba Plastic-UB 100pcs',
        variantSku: 'PL-UBSTRBOB-100',
        variantCostPrice: 50,
        variantSellingPrice: 99,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Material', value: 'Plastic' },
          { name: 'Style', value: 'UB' },
          { name: 'Quantity', value: '100pcs' },
        ],
      },
    ],
  },
  {
    productName: 'Straw Thin',
    productDescription: 'DPO Straw Thin Products',
    productStatus: 'Published',
    categoryName: 'PLASTIC PRODUCT',
    variants: [
      {
        variantName: 'Straw Thin Paper-Plain 100pcs',
        variantDescription: 'DPO Straw Thin Paper-Plain 100pcs',
        variantSku: 'PR-STRTPLN-100',
        variantCostPrice: 100,
        variantSellingPrice: 185,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Material', value: 'Paper' },
          { name: 'Style', value: 'Plain' },
          { name: 'Quantity', value: '100pcs' },
        ],
      },
      {
        variantName: 'Straw Thin Plastic-SCC 200pcs',
        variantDescription: 'DPO Straw Thin Plastic-SCC 200pcs',
        variantSku: 'PL-SCCSTR-200',
        variantCostPrice: 56,
        variantSellingPrice: 198,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Material', value: 'Plastic' },
          { name: 'Style', value: 'SCC' },
          { name: 'Quantity', value: '200pcs' },
        ],
      },
      {
        variantName: 'Straw Thin Plastic-Plain 100pcs',
        variantDescription: 'DPO Straw Thin Plastic-Plain 100pcs',
        variantSku: 'PL-STRTHNP-100',
        variantCostPrice: 25,
        variantSellingPrice: 50,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Material', value: 'Plastic' },
          { name: 'Style', value: 'Plain' },
          { name: 'Quantity', value: '100pcs' },
        ],
      },
      {
        variantName: 'Straw Thin Plastic-UB 200pcs',
        variantDescription: 'DPO Straw Thin Plastic-UB 200pcs',
        variantSku: 'PL-STRTHNUB-200',
        variantCostPrice: 56,
        variantSellingPrice: 198,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Material', value: 'Plastic' },
          { name: 'Style', value: 'UB' },
          { name: 'Quantity', value: '200pcs' },
        ],
      },
      {
        variantName: 'Straw Thin Plastic-UB 100pcs',
        variantDescription: 'DPO Straw Thin Plastic-UB 100pcs',
        variantSku: 'PL-STRTHNUB-100',
        variantCostPrice: 21,
        variantSellingPrice: 55,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Material', value: 'Plastic' },
          { name: 'Style', value: 'UB' },
          { name: 'Quantity', value: '100pcs' },
        ],
      },
    ],
  },
  {
    productName: 'Take-Out Plastic',
    productDescription: 'DPO Take-Out Plastic Products',
    productStatus: 'Published',
    categoryName: 'PLASTIC PRODUCT',
    variants: [
      {
        variantName: 'Take-Out Plastic Double-UB 100pcs',
        variantDescription: 'DPO Take-Out Plastic Double-UB 100pcs',
        variantSku: 'PL-UBTODBL-100',
        variantCostPrice: 85,
        variantSellingPrice: 120,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Size', value: 'Double' },
          { name: 'Style', value: 'UB' },
          { name: 'Quantity', value: '100pcs' },
        ],
      },
      {
        variantName: 'Take-Out Plastic Single-UB 100pcs',
        variantDescription: 'DPO Take-Out Plastic Single-UB 100pcs',
        variantSku: 'PL-UBTOSNGL-100',
        variantCostPrice: 56,
        variantSellingPrice: 95,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Size', value: 'Single' },
          { name: 'Style', value: 'UB' },
          { name: 'Quantity', value: '100pcs' },
        ],
      },
      {
        variantName: 'Take-out Plastic Single Plain LDPE 100pcs',
        variantDescription: 'DPO Take-out Plastic Single Plain LDPE 100pcs',
        variantSku: 'PL-LDPETOSNGPLN',
        variantCostPrice: 80,
        variantSellingPrice: 115,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Size', value: 'Single' },
          { name: 'Style', value: 'Plain LDPE' },
          { name: 'Quantity', value: '100pcs' },
        ],
      },
      {
        variantName: 'Take-out Plastic Big Size Plain LDPE 100pcs',
        variantDescription: 'DPO Take-out Plastic Big Size Plain LDPE 100pcs',
        variantSku: 'PL-LDPETOBIGSNGPLN',
        variantCostPrice: 322,
        variantSellingPrice: 464,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Size', value: 'Big Single' },
          { name: 'Style', value: 'Plain LDPE' },
          { name: 'Quantity', value: '100pcs' },
        ],
      },
    ],
  },
  {
    productName: 'Beverage Lid',
    productDescription: 'DPO Beverage Lid Products',
    productStatus: 'Published',
    categoryName: 'PLASTIC PRODUCT',
    variants: [
      {
        variantName: 'Double Beverage Lid White UB 90mm 50pcs per pack',
        variantDescription:
          'DPO Double Beverage Lid White UB 90mm 50pcs per pack',
        variantSku: 'PL-DBLELDWHI90mm',
        variantCostPrice: 45,
        variantSellingPrice: 60,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Color', value: 'White' },
          { name: 'Size', value: '90mm' },
          { name: 'Style', value: 'UB' },
          { name: 'Quantity', value: '50pcs' },
        ],
      },
    ],
  },
  {
    productName: 'RTE (Ready-to-Eat)',
    productDescription: 'DPO RTE (Ready-to-Eat) Products',
    productStatus: 'Published',
    categoryName: 'RTE',
    variants: [
      {
        variantName: 'RTE Buffalo Wing Rice Meal',
        variantDescription: 'DPO RTE Buffalo Wing Rice Meal',
        variantSku: 'RT-BUFFWING',
        variantCostPrice: 80,
        variantSellingPrice: 84,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Dish', value: 'Buffalo Wing' }],
      },
      {
        variantName: 'RTE Chicken Fillet Teriyaki Rice Meal',
        variantDescription: 'DPO RTE Chicken Fillet Teriyaki Rice Meal',
        variantSku: 'RT-CHKTERYKI',
        variantCostPrice: 80,
        variantSellingPrice: 84,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Dish', value: 'Chicken Fillet Teriyaki' }],
      },
      {
        variantName: 'RTE Fish W/ Tausi Rice Meal',
        variantDescription: 'DPO RTE Fish W/ Tausi Rice Meal',
        variantSku: 'RT-FISHTAUS',
        variantCostPrice: 80,
        variantSellingPrice: 84,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Dish', value: 'Fish with Tausi' }],
      },
      {
        variantName: 'RTE Grilled Pork Liempo Rice Meal',
        variantDescription: 'DPO RTE Grilled Pork Liempo Rice Meal',
        variantSku: 'RT-GRLPRKLMPO',
        variantCostPrice: 80,
        variantSellingPrice: 84,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Dish', value: 'Grilled Pork Liempo' }],
      },
      {
        variantName: 'RTE Pork Humba Rice Meal',
        variantDescription: 'DPO RTE Pork Humba Rice Meal',
        variantSku: 'RT-PRKHUM',
        variantCostPrice: 80,
        variantSellingPrice: 84,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Dish', value: 'Pork Humba' }],
      },
      {
        variantName: 'RTE Pork Sisig Rice Meal',
        variantDescription: 'DPO RTE Pork Sisig Rice Meal',
        variantSku: 'RT-PRKSSIG',
        variantCostPrice: 80,
        variantSellingPrice: 84,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Dish', value: 'Pork Sisig' }],
      },
      {
        variantName: 'RTE Pork Steak Rice Meal',
        variantDescription: 'DPO RTE Pork Steak Rice Meal',
        variantSku: 'RT-PRKSTEAK',
        variantCostPrice: 80,
        variantSellingPrice: 84,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Dish', value: 'Pork Steak' }],
      },
    ],
  },
  {
    productName: 'Gelato',
    productDescription: 'DPO Gelato Products',
    productStatus: 'Published',
    categoryName: 'GELATO',
    variants: [
      {
        variantName: 'Gelato Cafe Mocha 3L',
        variantDescription: 'DPO Gelato Cafe Mocha 3L',
        variantSku: 'GL-CFMOCHA-3L',
        variantCostPrice: 275,
        variantSellingPrice: 330,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Cafe Mocha' },
          { name: 'Volume', value: '3L' },
        ],
      },
      {
        variantName: 'Gelato Charcoal 3L',
        variantDescription: 'DPO Gelato Charcoal 3L',
        variantSku: 'GL-CHRCHOAL-3L',
        variantCostPrice: 275,
        variantSellingPrice: 330,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Charcoal' },
          { name: 'Volume', value: '3L' },
        ],
      },
      {
        variantName: 'Gelato Cookies and Cream 3L',
        variantDescription: 'DPO Gelato Cookies and Cream 3L',
        variantSku: 'GL-COKCRM-3L',
        variantCostPrice: 260,
        variantSellingPrice: 320,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Cookies and Cream' },
          { name: 'Volume', value: '3L' },
        ],
      },
      {
        variantName: 'Gelato Dark Chocolate 3L',
        variantDescription: 'DPO Gelato Dark Chocolate 3L',
        variantSku: 'GL-DRKCHLATE-3L',
        variantCostPrice: 275,
        variantSellingPrice: 330,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Dark Chocolate' },
          { name: 'Volume', value: '3L' },
        ],
      },
      {
        variantName: 'Gelato Mango 3L',
        variantDescription: 'DPO Gelato Mango 3L',
        variantSku: 'GL-MANGO-3L',
        variantCostPrice: 260,
        variantSellingPrice: 320,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Mango' },
          { name: 'Volume', value: '3L' },
        ],
      },
      {
        variantName: 'Gelato Matcha 3L',
        variantDescription: 'DPO Gelato Matcha 3L',
        variantSku: 'GL-MATCHA-3L',
        variantCostPrice: 275,
        variantSellingPrice: 330,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Matcha' },
          { name: 'Volume', value: '3L' },
        ],
      },
      {
        variantName: 'Gelato Milktea 3L',
        variantDescription: 'DPO Gelato Milktea 3L',
        variantSku: 'GL-MLTEA-3L',
        variantCostPrice: 260,
        variantSellingPrice: 320,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Milktea' },
          { name: 'Volume', value: '3L' },
        ],
      },
      {
        variantName: 'Gelato Red Velvet 3L',
        variantDescription: 'DPO Gelato Red Velvet 3L',
        variantSku: 'GL-REDVLVT-3L',
        variantCostPrice: 260,
        variantSellingPrice: 320,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Red Velvet' },
          { name: 'Volume', value: '3L' },
        ],
      },
      {
        variantName: 'Gelato Strawberry 3L',
        variantDescription: 'DPO Gelato Strawberry 3L',
        variantSku: 'GL-STRWBRY-3L',
        variantCostPrice: 260,
        variantSellingPrice: 320,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Strawberry' },
          { name: 'Volume', value: '3L' },
        ],
      },
      {
        variantName: 'Gelato Tableya 3L',
        variantDescription: 'DPO Gelato Tableya 3L',
        variantSku: 'GL-TABLYA-3L',
        variantCostPrice: 260,
        variantSellingPrice: 320,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Tableya' },
          { name: 'Volume', value: '3L' },
        ],
      },
      {
        variantName: 'Gelato Ube Taro 3L',
        variantDescription: 'DPO Gelato Ube Taro 3L',
        variantSku: 'GL-TARO-3L',
        variantCostPrice: 260,
        variantSellingPrice: 320,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Ube Taro' },
          { name: 'Volume', value: '3L' },
        ],
      },
      {
        variantName: 'Gelato Vanilla 3L',
        variantDescription: 'DPO Gelato Vanilla 3L',
        variantSku: 'GL-VANILLA-3L',
        variantCostPrice: 260,
        variantSellingPrice: 320,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Vanilla' },
          { name: 'Volume', value: '3L' },
        ],
      },
    ],
  },
  {
    productName: 'Cake',
    productDescription: 'DPO Cake Products',
    productStatus: 'Published',
    categoryName: 'BREAD AND PASTRIES',
    variants: [
      {
        variantName: 'Cake-Ube',
        variantDescription: 'DPO Cake-Ube',
        variantSku: 'CK-UBE',
        variantCostPrice: 520,
        variantSellingPrice: 720,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Flavor', value: 'Ube' }],
      },
      {
        variantName: 'Cake-Red Velvet',
        variantDescription: 'DPO Cake-Red Velvet',
        variantSku: 'CK-RDVLVT',
        variantCostPrice: 600,
        variantSellingPrice: 720,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Flavor', value: 'Red Velvet' }],
      },
      {
        variantName: 'Cake-Yema',
        variantDescription: 'DPO Cake-Yema',
        variantSku: 'CK-YMA',
        variantCostPrice: 470,
        variantSellingPrice: 575,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Flavor', value: 'Yema' }],
      },
      {
        variantName: 'Cake-Mango Cream',
        variantDescription: 'DPO Cake-Mango Cream',
        variantSku: 'CK-MNGOCRM',
        variantCostPrice: 650,
        variantSellingPrice: 720,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Flavor', value: 'Mango Cream' }],
      },
      {
        variantName: 'Cake-Coffee Caramel',
        variantDescription: 'DPO Cake-Coffee Caramel',
        variantSku: 'CK-COFECRML',
        variantCostPrice: 550,
        variantSellingPrice: 720,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Flavor', value: 'Coffee Caramel' }],
      },
      {
        variantName: 'Cake-Strawberry Short',
        variantDescription: 'DPO Cake-Strawberry Short',
        variantSku: 'CK-STWBRYSHRT',
        variantCostPrice: 650,
        variantSellingPrice: 750,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Flavor', value: 'Strawberry Short' }],
      },
      {
        variantName: 'Cake-Boston Cream Pie',
        variantDescription: 'DPO Cake-Boston Cream Pie',
        variantSku: 'CK-BSTNCRMPIE',
        variantCostPrice: 780,
        variantSellingPrice: 850,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Flavor', value: 'Boston Cream Pie' }],
      },
      {
        variantName: 'Cake-Chocolate Moist',
        variantDescription: 'DPO Cake-Chocolate Moist',
        variantSku: 'CK-MOIST',
        variantCostPrice: 500,
        variantSellingPrice: 720,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Flavor', value: 'Chocolate Moist' }],
      },
      {
        variantName: 'Cake-Custard',
        variantDescription: 'DPO Cake-Custard',
        variantSku: 'CK-CUSTRD',
        variantCostPrice: 400,
        variantSellingPrice: 520,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Flavor', value: 'Custard' }],
      },
      {
        variantName: 'Cake-Truffle',
        variantDescription: 'DPO Cake-Truffle',
        variantSku: 'CK-TRFLE',
        variantCostPrice: 750,
        variantSellingPrice: 820,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Flavor', value: 'Truffle' }],
      },
      {
        variantName: 'Cake-Cookies and Cream',
        variantDescription: 'DPO Cake-Cookies and Cream',
        variantSku: 'CK-COKISANDCRM',
        variantCostPrice: 580,
        variantSellingPrice: 720,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Flavor', value: 'Cookies and Cream' }],
      },
      {
        variantName: 'Cake-Banana Cream',
        variantDescription: 'DPO Cake-Banana Cream',
        variantSku: 'CK-BNACRM',
        variantCostPrice: 550,
        variantSellingPrice: 720,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Flavor', value: 'Banana Cream' }],
      },
      {
        variantName: 'Cake-Chocohazelnut Crunch',
        variantDescription: 'DPO Cake-Chocohazelnut Crunch',
        variantSku: 'CK-CHCOHZLNTCRM',
        variantCostPrice: 750,
        variantSellingPrice: 830,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [{ name: 'Flavor', value: 'Chocohazelnut Crunch' }],
      },
    ],
  },
  {
    productName: 'Frozen Food',
    productDescription: 'DPO Frozen Food Products',
    productStatus: 'Published',
    categoryName: 'FROZEN ITEM',
    variants: [
      {
        variantName: 'Bacon',
        variantDescription: 'DPO Bacon',
        variantSku: 'FI-BACON',
        variantCostPrice: 508.25,
        variantSellingPrice: 584.49,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Type', value: 'Bacon' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Chicken Nuggets',
        variantDescription: 'DPO Chicken Nuggets',
        variantSku: 'FI-CHINUG',
        variantCostPrice: 250,
        variantSellingPrice: 375,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Type', value: 'Chicken Nuggets' },
          { name: 'Quantity', value: '60pcs' },
        ],
      },
      {
        variantName: 'French Fries',
        variantDescription: 'DPO French Fries',
        variantSku: 'FI-FRCHFRS',
        variantCostPrice: 110,
        variantSellingPrice: 199,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Type', value: 'French Fries' },
          { name: 'Weight', value: '1kg' },
        ],
      },
    ],
  },
  {
    productName: 'Syrup',
    productDescription: 'DPO Syrup Products',
    productStatus: 'Published',
    categoryName: 'SYRUP',
    variants: [
      {
        variantName: 'Syrup Black Sugar 1L',
        variantDescription: 'DPO Syrup Black Sugar 1L',
        variantSku: 'SY-BLKSUG-1L',
        variantCostPrice: 253,
        variantSellingPrice: 350,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Black Sugar' },
          { name: 'Volume', value: '1L' },
        ],
      },
      {
        variantName: 'Syrup Fructose 1L',
        variantDescription: 'DPO Syrup Fructose 1L',
        variantSku: 'SY-FRUCTSE-1L',
        variantCostPrice: 88,
        variantSellingPrice: 125,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Fructose' },
          { name: 'Volume', value: '1L' },
        ],
      },
      {
        variantName: 'Syrup Hazelnut 750mL',
        variantDescription: 'DPO Syrup Hazelnut 750mL',
        variantSku: 'SY-HAZNUT-750',
        variantCostPrice: 245,
        variantSellingPrice: 275,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Hazelnut' },
          { name: 'Volume', value: '750mL' },
        ],
      },
      {
        variantName: 'Syrup Strawberry',
        variantDescription: 'DPO Syrup Strawberry',
        variantSku: 'SY-STRBRRY',
        variantCostPrice: 423,
        variantSellingPrice: 485,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Strawberry' },
          { name: 'Volume', value: '750mL' },
        ],
      },
      {
        variantName: 'Syrup Vanilla',
        variantDescription: 'DPO Syrup Vanilla',
        variantSku: 'SY-VANILL-1L',
        variantCostPrice: 81,
        variantSellingPrice: 299,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Vanilla' },
          { name: 'Volume', value: '1L' },
        ],
      },
    ],
  },
  {
    productName: 'Sauce',
    productDescription: 'DPO Sauce Products',
    productStatus: 'Published',
    categoryName: 'SAUCE',
    variants: [
      {
        variantName: 'Sauce Coleslaw Dip',
        variantDescription: 'DPO Sauce Coleslaw Dip',
        variantSku: 'SU-COLSDIP',
        variantCostPrice: 181.6,
        variantSellingPrice: 285,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Coleslaw Dip' },
          { name: 'Volume', value: '1L' },
        ],
      },
      {
        variantName: 'Sauce Aioli',
        variantDescription: 'DPO Sauce Aioli',
        variantSku: 'SU-AIOLI',
        variantCostPrice: 157.35,
        variantSellingPrice: 220,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Aioli' },
          { name: 'Volume', value: '1L' },
        ],
      },
      {
        variantName: 'Sauce Garlic Parmesan',
        variantDescription: 'DPO Sauce Garlic Parmesan',
        variantSku: 'SU-GARPARM',
        variantCostPrice: 173.44,
        variantSellingPrice: 225,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Garlic Parmesan' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Sauce Mayo Spicy',
        variantDescription: 'DPO Sauce Mayo Spicy',
        variantSku: 'SU-MAYSPIC',
        variantCostPrice: 192.51,
        variantSellingPrice: 279,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Mayo Spicy' },
          { name: 'Volume', value: '1L' },
        ],
      },
      {
        variantName: 'Sauce Mustard 1kg',
        variantDescription: 'DPO Sauce Mustard 1kg',
        variantSku: 'SU-MUSTRD-1K',
        variantCostPrice: 220,
        variantSellingPrice: 280,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Mustard' },
          { name: 'Weight', value: '1kg' },
        ],
      },
      {
        variantName: 'Sauce Pesto',
        variantDescription: 'DPO Sauce Pesto',
        variantSku: 'SU-PESTO',
        variantCostPrice: 680.07,
        variantSellingPrice: 800,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Pesto' },
          { name: 'Volume', value: '1L' },
        ],
      },
      {
        variantName: 'Sauce Spicy Hickory',
        variantDescription: 'DPO Sauce Spicy Hickory',
        variantSku: 'SU-SPICHIC',
        variantCostPrice: 174.71,
        variantSellingPrice: 265,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Spicy Hickory' },
          { name: 'Volume', value: '1L' },
        ],
      },
      {
        variantName: 'Sauce Teriyaki',
        variantDescription: 'DPO Sauce Teriyaki',
        variantSku: 'SU-TERYKI',
        variantCostPrice: 177.3,
        variantSellingPrice: 222,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Teriyaki' },
          { name: 'Volume', value: '1L' },
        ],
      },
      {
        variantName: 'Sauce Tonkatsu',
        variantDescription: 'DPO Sauce Tonkatsu',
        variantSku: 'SU-TONKATS',
        variantCostPrice: 243.92,
        variantSellingPrice: 280,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Tonkatsu' },
          { name: 'Volume', value: '1L' },
        ],
      },
      {
        variantName: 'Sauce Red',
        variantDescription: 'DPO Sauce Red',
        variantSku: 'SU-REDSAU',
        variantCostPrice: 154.68,
        variantSellingPrice: 200,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Red' },
          { name: 'Volume', value: '1L' },
        ],
      },
      {
        variantName: 'Sauce White',
        variantDescription: 'DPO Sauce White',
        variantSku: 'SU-WHISAU',
        variantCostPrice: 144.05,
        variantSellingPrice: 185,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'White' },
          { name: 'Volume', value: '1L' },
        ],
      },
      {
        variantName: 'Thousand Island Dressing',
        variantDescription: 'DPO Thousand Island Dressing',
        variantSku: 'SU-THISLDRS',
        variantCostPrice: 210,
        variantSellingPrice: 250,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Thousand Island' },
          { name: 'Weight', value: '1kg' },
        ],
      },
    ],
  },
  {
    productName: 'Filling',
    productDescription: 'DPO Filling Products',
    productStatus: 'Published',
    categoryName: 'SAUCE',
    variants: [
      {
        variantName: 'Pistachio Filling 1Kg',
        variantDescription: 'DPO Pistachio Filling 1Kg',
        variantSku: 'SU-PSTCIOFLNG1KG',
        variantCostPrice: 1999,
        variantSellingPrice: 2150,
        variantStatus: 'Active',
        variantMinimumOrder: 1,
        attributes: [
          { name: 'Flavor', value: 'Pistachio' },
          { name: 'Weight', value: '1kg' },
        ],
      },
    ],
  },
];
